name: Deploy ASP.NET Core App to Azure  

on:  
  push:  
    branches:  
      - main  

permissions:  
  id-token: write  
  contents: read  

jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  

    env:  
      AZURE_WEBAPP_NAME: MySuperUniqueWebApp
      AZURE_WEBAPP_PACKAGE_PATH: '.'  
      DOTNET_VERSION: '8.0.x'  

    steps:  
      - name: Checkout the repository  
        uses: actions/checkout@v3  

      - name: Log in to Azure  
        uses: azure/login@v2  
        with:  
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

      - name: Set up .NET Core SDK  
        uses: actions/setup-dotnet@v3  
        with:  
          dotnet-version: ${{ env.DOTNET_VERSION }}  

      - name: Restore dependencies  
        run: dotnet restore MyAspNetApp/MyAspNetApp.csproj

      - name: Build the project  
        run: dotnet build MyAspNetApp/MyAspNetApp.csproj --configuration Release  

      - name: Publish the project  
        run: dotnet publish MyAspNetApp/MyAspNetApp.csproj -c Release --output ./publish  

      - name: Deploy to Azure Web App  
        uses: azure/webapps-deploy@v3  
        with:  
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  
          package: ./publish  

      - name: Logout from Azure  
        run: az logout
